using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Session_14.Model
{
    public enum Brands
    {
        Abarth,
        Acura,
        AlfaRomeo,
        AstonMartin,
        Audi,
        Bentley,
        BMW,
        Bugati,
        Buick,
        Cadillac,
        Chevrolet,
        Chrysler,
        Citroen,
        Dacia,
        Dodg,
        Ferrari,
        Fiat,
        Ford,
        GMC,
        Honda,
        Hummer,
        Hyundai,
        Infiniti,
        Isuzu,
        Jaguar,
        Jeep,
        Kia,
        Lamborghini,
        Lancia,
        LandRover,
        Lexus,
        Lincoln,
        Lotus,
        Maserati,
        Maybach,
        Mazda,
        McLaren,
        MercedesBenz,
        Mercury,
        MiniCooper,
        Mitsubishi,
        Nissan,
        Opel,
        Peugeot,
        Pontiac,
        Porsche,
        Ram,
        Renault,
        RollsRoyce,
        Saab,
        Saturn,
        Scion,
        Seat,
        Skoda,
        Smart,
        SsangYong,
        Subaru,
        Suzuki,
        Tesla,
        Toyota,
        Volkswagen,
        Volvo,
        Wiesmann
    }
}
